config/routes.rb
Rails.application.routes.draw do
  resources :users do
      collection do
    get 'download', to: 'users#download' # Use 'to' instead of 'action' for clarity
  end
  end
  resources :roles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users, dependent: :destroy
end  

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/roles_controller.rb
# frozen_string_literal: true

# app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: %i[show edit update destroy]

  def index
    per_page = params[:per_page] || 10
    @roles = Role.all.paginate(page: params[:page], per_page: per_page)
    @role_user_counts = Role.includes(:users).to_h { |role| [role.id, role.users.count] }
  end

  def show; end

  def new
    @role = Role.new
  end

  def edit; end

  def create
    @role = Role.new(role_params)

    if @role.save
      redirect_to @role, notice: 'Role was successfully created.'
    else
      render :new
    end
  end

  def update
    if @role.update(role_params)
      redirect_to @role, notice: 'Role was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @role.destroy
    redirect_to roles_url, notice: 'Role was successfully destroyed.'
  end

  private

  def set_role
    @role = Role.find(params[:id])
  end

  def role_params
    params.require(:role).permit(:name)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    per_page = params[:per_page] || 10
    if params[:role_id].present?
      role = Role.find(params[:role_id])
      @users = role.users.order(:id).paginate(page: params[:page], per_page: per_page)
    else
      @users = User.order(:id).paginate(page: params[:page], per_page: per_page)
    end
  end

  def new
    @user = User.new
    @roles = Role.all
  end

  def edit
    @roles = Role.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.with(user: @user).welcome_email.deliver_now
      redirect_to @user, notice: 'User was successfully created.'
    else
      @roles = Role.all
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      @roles = Role.all
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  def download
    @users = User.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'user_details', template: 'users/download'
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :role_id, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserManagementSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/roles/_form.html.erb
<%= form_with(model: role) do |form| %>
  <% if role.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% role.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/_role.html.erb
<div id="<%= dom_id role %>">
  <p>
    <strong>Name:</strong>
    <%= role.name %>
  </p>

</div>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Show this role", @role %> |
  <%= link_to "Back to roles", roles_path %>
</div>

app/views/roles/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roles</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<div class="container">
  <h1>Roles</h1>

  <%= form_tag(roles_path, method: :get) do %>
    <div class="form-group">
      <%= label_tag :per_page, "Records per page:" %>
      <%= number_field_tag :per_page, params[:per_page] || 10, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :page, "Page number:" %>
      <%= number_field_tag :page, params[:page] || 1, class: 'form-control' %>
    </div>
    <%= submit_tag 'Apply', class: 'btn btn-primary' %>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Actions</th>
        <th>Users Count</th>
      </tr>
    </thead>
    <tbody>
      <% @roles.each do |role| %>
        <tr>
          <td><%= role.name %></td>
          <td>
            <%= link_to 'Show', role, class: 'btn btn-primary btn-sm' %>
            <%= link_to 'Edit', edit_role_path(role), class: 'btn btn-warning btn-sm' %>
            <%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
          <td><%= @role_user_counts[role.id] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @roles, params: { per_page: params[:per_page], page: params[:page] } %>

  <%= link_to 'New Role', new_role_path, class: 'btn btn-success' %>
</div>

</body>
</html>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Back to roles", roles_path %>
</div>

app/views/roles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @role %>

<div>
  <%= link_to "Edit this role", edit_role_path(@role) %> |
  <%= link_to "Back to roles", roles_path %>

  <%= button_to "Destroy this role", @role, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

    <div >
    <%= form.label :role_id %>
    <%= form.select :role_id, options_for_select(@roles.map { |role| [role.name, role.id] }) %>
  </div>

<div>
  <%= form.label :image, "Upload file", style: "display: block; cursor: pointer;" %>
  <%= form.file_field :image, style: "display: none;", onchange: "displayFileName(this)" %>
  <%= form.text_field :image, placeholder: "No file chosen", readonly: true, onclick: "selectFile()" %>
</div>

<script>
  function selectFile() {
    document.querySelector('input[type="file"]').click();
  }

  function displayFileName(input) {
    if (input.files.length > 0) {
      const fileName = input.files[0].name;
      const textField = input.parentNode.querySelector('input[type="text"]');
      textField.value = fileName;
    }
  }
</script>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= user.role_id %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= user.image %>
  </p>

</div>

app/views/users/download.pdf.erb
<!DOCTYPE html>
<html>
<head>
  <title>User Details PDF</title>
</head>
<body>
  <h1>User Details</h1>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= @users.id %></td>
          <td><%= @users.first_name %></td>
          <td><%= @users.last_name %></td>
        </tr>
    </tbody>
  </table>
</body>
</html>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Users</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<div class="container">
  <h1>Users</h1>

  <%= form_tag(users_path, method: :get) do %>
    <div class="form-group">
      <%= label_tag :per_page, "Records per page:" %>
      <%= number_field_tag :per_page, params[:per_page] || 10, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :page, "Page number:" %>
      <%= number_field_tag :page, params[:page] || 1, class: 'form-control' %>
    </div>
    <%= submit_tag 'Apply', class: 'btn btn-primary' %>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Role</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.role.name %></td>
          <td>
            <%= link_to 'Show', user, class: 'btn btn-primary btn-sm' %>
            <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-warning btn-sm' %>
            <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @users, params: { per_page: params[:per_page], page: params[:page] } %>

  <%= link_to 'New User', new_user_path, class: 'btn btn-success' %>
</div>

</body>
</html>

app/views/users/index.pdf.erb
<h1>Users List</h1>
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Role</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.role.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<%= form_with(model: @user, local: true) do |form| %>

  <!-- Other form fields... -->


  <!-- Other form fields... -->

<% end %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

<%= link_to 'Download User Details', download_users_path(format: :pdf, id: @user.id), class: 'btn btn-primary' %>



  <%= button_to "Destroy this user", @user, method: :delete %>
</div>